/*******************************************************************************
 * Copyright (C) 2011 - 2015 Yoav Artzi, All rights reserved.
 * <p>
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or any later version.
 * <p>
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 * <p>
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *******************************************************************************/
package edu.cornell.cs.nlp.spf.learn.validation;

import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.function.Predicate;
import java.util.Random;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.Math;
import java.net.MalformedURLException;

import edu.cornell.cs.nlp.spf.ccg.categories.ICategoryServices;
import edu.cornell.cs.nlp.spf.ccg.lexicon.ILexiconImmutable;
import edu.cornell.cs.nlp.spf.ccg.lexicon.LexicalEntry;
import edu.cornell.cs.nlp.spf.data.IDataItem;
import edu.cornell.cs.nlp.spf.data.ILabeledDataItem;
import edu.cornell.cs.nlp.spf.data.collection.IDataCollection;
import edu.cornell.cs.nlp.spf.genlex.ccg.ILexiconGenerator;
import edu.cornell.cs.nlp.spf.genlex.ccg.LexiconGenerationServices;
import edu.cornell.cs.nlp.spf.learn.ILearner;
import edu.cornell.cs.nlp.spf.learn.LearningStats;
import edu.cornell.cs.nlp.spf.learn.validation.perceptron.ValidationPerceptron;
import edu.cornell.cs.nlp.spf.learn.validation.stocgrad.ValidationStocGrad;
import edu.cornell.cs.nlp.spf.parser.IDerivation;
import edu.cornell.cs.nlp.spf.parser.IOutputLogger;
import edu.cornell.cs.nlp.spf.parser.IParserOutput;
import edu.cornell.cs.nlp.spf.parser.ParsingOp;
import edu.cornell.cs.nlp.spf.parser.ccg.IWeightedParseStep;
import edu.cornell.cs.nlp.spf.parser.ccg.model.IDataItemModel;
import edu.cornell.cs.nlp.spf.parser.ccg.model.IModelImmutable;
import edu.cornell.cs.nlp.spf.parser.ccg.model.Model;
import edu.cornell.cs.nlp.spf.parser.filter.IParsingFilterFactory;
import edu.cornell.cs.nlp.utils.collections.CollectionUtils;
import edu.cornell.cs.nlp.utils.filter.IFilter;
import edu.cornell.cs.nlp.utils.log.ILogger;
import edu.cornell.cs.nlp.utils.log.LoggerFactory;
import edu.cornell.cs.nlp.utils.system.MemoryReport;

/**
 * Validation-based learner. See Artzi and Zettlemoyer 2013 for detailed
 * description. While the algorithm in the paper is situated, this one is not.
 * For a situated version see the package edu.uw.cs.lil.tiny.learn.situated.
 * <p>
 * The learner is insensitive to the syntactic category generated by the
 * inference procedure -- only the semantic portion is being validated. However,
 * parsers can be constrained to output only specific syntactic categories, see
 * the parser builders.
 * </p>
 * <p>
 * Parameter update step inspired by: Natasha Singh-Miller and Michael Collins.
 * 2007. Trigger-based Language Modeling using a Loss-sensitive Perceptron
 * Algorithm. In proceedings of ICASSP 2007.
 * </p>
 *
 * @author Yoav Artzi
 * @see ValidationPerceptron
 * @see ValidationStocGrad
 */
public abstract class AbstractLearner<SAMPLE extends IDataItem<?>, DI extends ILabeledDataItem<SAMPLE, ?>, PO extends IParserOutput<MR>, MR>
		implements ILearner<SAMPLE, DI, Model<SAMPLE, MR>> {
	public static final ILogger												LOG					= LoggerFactory
			.create(AbstractLearner.class);

	protected static final String											GOLD_LF_IS_MAX		= "G";
	protected static final String											HAS_VALID_LF		= "V";
	protected static final String											TRIGGERED_UPDATE	= "U";

	private final ICategoryServices<MR>										categoryServices;

	/**
	 * Recycle the lexical induction parser output as the pruned one for
	 * parameter update.
	 */
	protected final boolean													conflateGenlexAndPrunedParses;

	/**
	 * Number of training epochs.
	 */
	protected final int														epochs;
	
	/**
	 * The learner is error driven, meaning: if it can parse a sentence, it will
	 * skip lexical induction.
	 */
	protected final boolean													errorDriven;

	/**
	 * GENLEX procedure. If 'null', skip lexicon learning.
	 */
	protected final ILexiconGenerator<DI, MR, IModelImmutable<SAMPLE, MR>>	genlex;

	/**
	 * Parser beam size for lexical generation.
	 */
	private final Integer													lexiconGenerationBeamSize;

	protected final IParsingFilterFactory<DI, MR>								parsingFilterFactory;

	protected final IFilter<DI>												processingFilter;

	/**
	 * Training data.
	 */
	protected final IDataCollection<DI>										trainingData;

	/**
	 * Mapping of training data samples to their gold labels.
	 */
	private final Map<DI, MR>												trainingDataDebug;

	/**
	 * Parser output logger.
	 */
	protected final IOutputLogger<MR>										parserOutputLogger;

	/**
	 * Learning statistics.
	 */
	protected final LearningStats<DI>											stats;

	
	/** -------------------- added by Candace ----------------------------
	 * adding global parameters for equality metric & saving stats
	 */
	protected final String 												parentDirectory;
	/** -------------------- added by Candace ----------------------------
	 * amount of training noise to simulate vision system
	 */
	protected final double 												trainingNoise;
	protected final int													numNoisyExamples;
	protected final Random												rng 				= new Random();	
	
	
	protected final boolean												runModelBeforeTraining;
	
	protected final boolean												skipToTest;
	
	/** 
	 * 
	 * @param numIterations
	 * @param trainingData
	 * @param trainingDataDebug
	 * @param lexiconGenerationBeamSize
	 * @param parserOutputLogger
	 * @param conflateGenlexAndPrunedParses
	 * @param errorDriven
	 * @param categoryServices
	 * @param genlex
	 * @param processingFilter
	 * @param parsingFilterFactory
	 * @param parentDirectory
	 * @param trainingNoise
	 * @param runModelBeforeTraining
	 */
	
	protected AbstractLearner(int numIterations,
			IDataCollection<DI> trainingData, Map<DI, MR> trainingDataDebug,
			int lexiconGenerationBeamSize, IOutputLogger<MR> parserOutputLogger,
			boolean conflateGenlexAndPrunedParses, boolean errorDriven,
			ICategoryServices<MR> categoryServices,
			ILexiconGenerator<DI, MR, IModelImmutable<SAMPLE, MR>> genlex,
			IFilter<DI> processingFilter, IParsingFilterFactory<DI, MR> parsingFilterFactory,
			String parentDirectory, double trainingNoise,
			boolean runModelBeforeTraining, boolean skipToTest) {
		this.epochs = numIterations;
		this.trainingData = trainingData;
		this.trainingDataDebug = trainingDataDebug;
		this.lexiconGenerationBeamSize = lexiconGenerationBeamSize;
		this.parserOutputLogger = parserOutputLogger;
		this.conflateGenlexAndPrunedParses = conflateGenlexAndPrunedParses;
		this.errorDriven = errorDriven;
		this.categoryServices = categoryServices;
		this.genlex = genlex;
		this.processingFilter = processingFilter;
		this.parsingFilterFactory = parsingFilterFactory;
		this.stats = new LearningStats.Builder<DI>(trainingData.size(), epochs)
				.addStat(HAS_VALID_LF, "Has a valid parse")
				.addStat(TRIGGERED_UPDATE, "Sample triggered update")
				.addStat(GOLD_LF_IS_MAX,
						"The best-scoring LF equals the provided GOLD debug LF")
				.setNumberStat("Number of new lexical entries added").build();
		/** -------------------- added by Candace ---------------------------- **/
		this.parentDirectory = parentDirectory;
		this.trainingNoise = trainingNoise;
		this.numNoisyExamples = ((int) Math.ceil(  ((double) trainingData.size()) * this.trainingNoise)); // meh not very pretty
		this.runModelBeforeTraining = runModelBeforeTraining;
		this.skipToTest = skipToTest;
	}
	
	@Override
	public void train(Model<SAMPLE, MR> model) {
		if (runModelBeforeTraining){
			runInitialModel(model);
		}
		
		// Init GENLEX.
		LOG.info("Initializing GENLEX ...\n");
		genlex.init(model);
		
		// Epochs
		if (model.getSeedBenchmark() || skipToTest){
			System.out.println("not training");
			return;
		}
			
		for (int epochNumber = 0; epochNumber < epochs; ++epochNumber) {
			runSingleEpoch(model, epochNumber);
		}

		// Write stats
		recordFinalStats(epochs);
		writeFinalLexiconToFile(model);
	}
	
	protected void runSingleEpoch(Model<SAMPLE, MR> model, int epochNumber){
		LOG.info("=========================");
		LOG.info("Training epoch %d", epochNumber);
		LOG.info("=========================");
		System.out.println("=========================" + 
							"Training epoch " + epochNumber + 
							"=========================");
		
		int itemCounter = -1;
		final HashSet<Integer> noisyExamples = generateNoisyExamples();
		
		for (final DI dataItem : trainingData) {
			
			// print update of where we are in training data
			if ( (itemCounter+1) % 50 == 0 ){
				System.out.println("on example " + (itemCounter+1) + " of " + trainingData.size());
			}
			
			
			// Process a single training sample

			// Record start time
			final long startTime = System.currentTimeMillis();

			// Log sample header
			LOG.info("%d : ================== [%d]", ++itemCounter, epochNumber);
			LOG.info("Sample type: %s", dataItem.getClass().getSimpleName());
			LOG.info("%s", dataItem);

			// Skip sample, if over the length limit
			if (!processingFilter.test(dataItem)) {
				LOG.info(
						"Skipped training sample, due to processing filter");
				continue;
			}

			stats.count("Processed", epochNumber);

			try {
				// Data item model
				final IDataItemModel<MR> dataItemModel = model.createDataItemModel(dataItem.getSample());
				
				// ///////////////////////////
				// Step I: Parse with current model. If we get a valid
				// parse, update parameters.
				// ///////////////////////////

				// Parse with current model and record some statistics
				final PO parserOutput = parse(dataItem, dataItemModel);
				stats.mean("Model parse",
						parserOutput.getParsingTime() / 1000.0, "sec");
				parserOutputLogger.log(parserOutput, dataItemModel, String
						.format("train-%d-%d", epochNumber, itemCounter));
				
				final List<? extends IDerivation<MR>> modelParses = parserOutput.getAllDerivations();
				

				LOG.info("Model parsing time: %.4fsec", parserOutput.getParsingTime() / 1000.0);
				LOG.info("Output is %s", parserOutput.isExact() ? "exact" : "approximate");
				LOG.info("Created %d model parses for training sample:", modelParses.size());
				for (final IDerivation<MR> parse : modelParses) {
					logParse(dataItem, parse,
							validate(dataItem, parse.getSemantics()), true,
							dataItemModel);
				}
				
				// Create a list of all valid parses
				final List<? extends IDerivation<MR>> validParses = getValidParses(parserOutput, dataItem);
				
				/*
				for (final IDerivation<MR> parse : modelParses){
					System.out.println("model " + parse + " " + validParses.contains(parse));
					
				}
				for (final IDerivation<MR> parse : validParses){
					System.out.println("valid " + parse
											+ "\n" + parse.getMaxLexicalEntries() + "\n\n");
				}
				*/
				
				
				if (validParses.size() > 0){ // at least one valid parse
					if (noisyExamples.contains(itemCounter)){ // example is noise so skip parameter update
						if (rng.nextInt(trainingData.size()) == 0){
							stats.addNewIncorrectParse(epochNumber);
						} else {
							stats.addNewFailureParse(epochNumber);
						}
					} else { // example is not noise, so do parameter update
						stats.addNewCorrectParse(epochNumber);
						if (errorDriven){
							
							// call parameter update procedure and continue
							parameterUpdate(dataItem, parserOutput, parserOutput,
									model, itemCounter, epochNumber, false);
							continue;
						}
					}
				} else if (modelParses.size() > 0){
					if (noisyExamples.contains(itemCounter)){ // example is noise, so pretend parses are valid and do parameter update
						stats.addNewCorrectParse(epochNumber);
						
						if (errorDriven){
							// call parameter update procedure and continue
							parameterUpdate(dataItem, parserOutput, parserOutput,
									model, itemCounter, epochNumber, true);
							continue;
						}
					} else { // example is not noise so do parameter update
						stats.addNewIncorrectParse(epochNumber);
					}
				} else { // no parses found
					if (noisyExamples.contains(itemCounter)){ // example is noise, so pretend parse exists and update
						stats.addNewCorrectParse(epochNumber);
						
						if (errorDriven){
							// call parameter update procedure and continue
							parameterUpdate(dataItem, parserOutput, parserOutput,
									model, itemCounter, epochNumber, true);
							continue;
						}
					}else { // example is not noise
						stats.addNewFailureParse(epochNumber);
					}
					
				}

				// ///////////////////////////
				// Step II: Generate new lexical entries, prune and update
				// the model. Keep the parser output for Step III.
				// ///////////////////////////

				if (genlex == null) {
					// Skip the example if not doing lexicon learning
					continue;
				}

				final PO generationParserOutput = lexicalInduction(dataItem,
						itemCounter, dataItemModel, model, epochNumber);	
				
				// ///////////////////////////
				// Step III: Update parameters
				// ///////////////////////////
				if (conflateGenlexAndPrunedParses && generationParserOutput != null) {
						parameterUpdate(dataItem, parserOutput,
								generationParserOutput, model, itemCounter,
								epochNumber, noisyExamples.contains(itemCounter));
				} else {
					final PO prunedParserOutput = parse(dataItem,
							parsingFilterFactory.create(dataItem),
							dataItemModel);
					
					LOG.info("Conditioned parsing time: %.4fsec",
							prunedParserOutput.getParsingTime() / 1000.0);
					parserOutputLogger.log(prunedParserOutput,
							dataItemModel,
							String.format("train-%d-%d-conditioned",
									epochNumber, itemCounter));
					
					parameterUpdate(dataItem, parserOutput,
							prunedParserOutput, model, itemCounter,
							epochNumber, noisyExamples.contains(itemCounter));
				}


				LOG.info("current avg precision: "+ stats.getAveragePrecision());
				LOG.info("current avg recall: "+ stats.getAverageRecall());
				LOG.info("current avg f1: "+ stats.getAverageF1());
			} catch (IOException e) {
				e.printStackTrace();
			} finally {
				// Record statistics.
				stats.mean("Sample processing",
						(System.currentTimeMillis() - startTime) / 1000.0,
						"sec");
				LOG.info("Total sample handling time: %.4fsec",
						(System.currentTimeMillis() - startTime) / 1000.0);
			}
		}
		
		
		// Output epoch statistics
		LOG.info("System memory: %s", MemoryReport.generate());
		LOG.info("Epoch stats:");
		LOG.info(stats);
		
		// Compute epoch stats		
		System.out.println("precision: " + stats.getPrecision(epochNumber) +
							" recall " + stats.getRecall(epochNumber) +  
							" f1 " + stats.getF1(epochNumber));
		LOG.info("precision: " + stats.getPrecision(epochNumber) +
				" recall " + stats.getRecall(epochNumber) +  
				" f1 " + stats.getF1(epochNumber));
	}
	
	protected final void recordFinalStats(int epochs){
		stats.writeAveragesToFile(String.format("%s/logs/trends_train.txt", this.parentDirectory),
				trainingData.size());
		
		final BufferedWriter bw;
		try {
			bw = new BufferedWriter(new FileWriter (String.format("%s/logs/trends_train.txt", this.parentDirectory)));
			
			bw.write(String.format("Initial training precision: %f\n", stats.getPrecision(0)));
			bw.write(String.format("Initial training recall: %f\n", stats.getRecall(0)));
			bw.write(String.format("Initial training F1: %f\n", stats.getF1(0)));
			
			bw.write(String.format("Final training precision: %f\n", stats.getPrecision(epochs-1)));
			bw.write(String.format("Final training recall: %f\n", stats.getRecall(epochs-1)));
			bw.write(String.format("Final training F1: %f\n", stats.getF1(epochs-1)));
			
			bw.close();
		} catch (IOException e){
			e.printStackTrace();
		}
			
			
		LOG.info("Num/sentences in training set: " + trainingData.size());
	}
	
	protected final void writeFinalLexiconToFile(Model<SAMPLE, MR> model){		
		BufferedWriter bw = null;
		
		try {
			bw = new BufferedWriter(new FileWriter(String.format("%s/logs/final_lexicon.txt", this.parentDirectory)));
			bw.write("total number of entries in seed: " 		+ model.getSeedLexicon().getNumEntries() + "\n");
			bw.write("total number of entries in final: " 		+ model.getLexicon().getNumEntries() + "\n");
			bw.write("total number of learned entries: " 		+ model.getNumLearnedEntries() + "\n");
			bw.write("total number of empty entries: " 			+ model.getLexicon().getNumEmptySemanticsEntries() + "\n");
			// TODO fix this below
			//bw.write("average number of entries per token: " 	+ model.getLexicon().getAvgNumEntriesPerToken() + "\n");
			
			for(LexicalEntry<MR> entry : model.getLexicon().toCollection()){
				bw.write(entry + "\n");
			}
		} catch (IOException e){
			e.printStackTrace();
		} finally{
			try{
				bw.close();
			} catch (IOException ex){
				ex.printStackTrace();
			}
		}
	}
	
	protected final HashSet<Integer> generateNoisyExamples(){
		HashSet<Integer> noisyExamples = new HashSet<Integer>();  
		while (noisyExamples.size() < numNoisyExamples){
			noisyExamples.add(rng.nextInt(trainingData.size()));
		}
		return noisyExamples;
	}

	protected List<? extends IDerivation<MR>> getValidParses(PO parserOutput,
			final DI dataItem) {
		final List<? extends IDerivation<MR>> parses = new LinkedList<IDerivation<MR>>(
				parserOutput.getAllDerivations());
		
		// Use validation function to prune generation parses. Syntax is not
		// used to distinguish between derivations.
		CollectionUtils.filterInPlace(parses,
				e -> {
					try{
						return validate(dataItem, e.getSemantics());
					} catch (IOException e1) {
						e1.printStackTrace();
					}
					return false;
				});
		return parses;
	}
	
	protected PO lexicalInduction(final DI dataItem, int dataItemNumber,
			IDataItemModel<MR> dataItemModel, Model<SAMPLE, MR> model,
			int epochNumber) {
		
		
		// Generate lexical entries
		final ILexiconImmutable<MR> generatedLexicon = genlex.generate(dataItem, model, categoryServices);
		LOG.info("Generated lexicon size = %d", generatedLexicon.size());
		
		if (generatedLexicon.size() > 0) {
			// Case generated lexical entries

			// Create pruning filter, if the data item fits
			final Predicate<ParsingOp<MR>> pruningFilter = parsingFilterFactory.create(dataItem);

			// Parse with generated lexicon
			final PO parserOutput = parse(dataItem, pruningFilter, dataItemModel,
											generatedLexicon, lexiconGenerationBeamSize);
			
			// Log lexical generation parsing time
			stats.mean("genlex parse", parserOutput.getParsingTime() / 1000.0,
					"sec");
			LOG.info("Lexicon induction parsing time: %.4fsec",
					parserOutput.getParsingTime() / 1000.0);
			LOG.info("Output is %s",
					parserOutput.isExact() ? "exact" : "approximate");

			// Log generation parser output
			parserOutputLogger.log(parserOutput, dataItemModel, String
					.format("train-%d-%d-genlex", epochNumber, dataItemNumber));

			LOG.info("Created %d lexicon generation parses for training sample",
					parserOutput.getAllDerivations().size());

			// Get valid lexical generation parses
			final List<? extends IDerivation<MR>> validParses = getValidParses(
					parserOutput, dataItem);
			LOG.info("Removed %d invalid parses",
					parserOutput.getAllDerivations().size()
							- validParses.size());

			// Collect max scoring valid generation parses
			final List<IDerivation<MR>> bestGenerationParses = new LinkedList<IDerivation<MR>>();
			double currentMaxModelScore = -Double.MAX_VALUE;

			for (final IDerivation<MR> parse : validParses) {
				parse.getAverageMaxFeatureVector();
				
				// all parses
				if (parse.getScore() > currentMaxModelScore) {
					currentMaxModelScore = parse.getScore();
					bestGenerationParses.clear();
					bestGenerationParses.add(parse);
				} else if (parse.getScore() == currentMaxModelScore) {
					bestGenerationParses.add(parse);
				}
			}
			
			LOG.info("%d valid best parses for lexical generation:",
					bestGenerationParses.size());
			for (final IDerivation<MR> parse : bestGenerationParses) {
				logParse(dataItem, parse, true, true, dataItemModel);
			}

			// Update the model's lexicon with generated lexical
			// entries from the max scoring valid generation parses
			int newLexicalEntries = 0;
			for (final IDerivation<MR> parse : bestGenerationParses) {
				for (final LexicalEntry<MR> entry : parse
						.getMaxLexicalEntries()) {
					if (genlex.isGenerated(entry)) {
						if (model.addLexEntry(
								LexiconGenerationServices.unmark(entry))) {
							++newLexicalEntries;
							LOG.info("Added LexicalEntry to model: %s [%s]",
									entry, model.getTheta().printValues(
											model.computeFeatures(entry)));
						}
						// Lexical generators might link related lexical
						// entries, so if we add the original one, we
						// should also add all its linked ones
						for (final LexicalEntry<MR> linkedEntry : entry
								.getLinkedEntries()) {
							if (model.addLexEntry(LexiconGenerationServices
									.unmark(linkedEntry))) {
								++newLexicalEntries;
								LOG.info(
										"Added (linked) LexicalEntry to model: %s [%s]",
										linkedEntry,
										model.getTheta().printValues(model
												.computeFeatures(linkedEntry)));
							}
						}
					}
				}
			}
			// Record statistics
			if (newLexicalEntries > 0) {
				stats.appendSampleStat(dataItemNumber, epochNumber,
						newLexicalEntries);
			}

			return parserOutput;
		} else {
			// Skip lexical induction
			LOG.info("Skipped GENLEX step. No generated lexical items.");
			return null;
		}
	}

	protected boolean isGoldDebugCorrect(DI dataItem, MR label) {
		if (trainingDataDebug.containsKey(dataItem)) {
			try {
				return validate(dataItem, label);
			} catch (IOException e) {
				LOG.info(e.getMessage());
				System.exit(-1); // TODO clean up
				return false;
			}
		} else {
			return false;
		}
	}

	protected void logParse(DI dataItem, IDerivation<MR> parse, Boolean valid,
			boolean verbose, IDataItemModel<MR> dataItemModel) {
		logParse(dataItem, parse, valid, verbose, null, dataItemModel);
	}

	protected void logParse(DI dataItem, IDerivation<MR> parse, Boolean valid,
			boolean verbose, String tag, IDataItemModel<MR> dataItemModel) {
		final boolean isGold;
		if (isGoldDebugCorrect(dataItem, parse.getSemantics())) {
			isGold = true;
		} else {
			isGold = false;
		}
		LOG.info("%s%s[%.2f%s] %s", isGold ? "* " : "  ",
				tag == null ? "" : tag + " ", parse.getScore(),
				valid == null ? "" : valid ? ", V" : ", X", parse);
		if (verbose) {
			for (final IWeightedParseStep<MR> step : parse.getMaxSteps()) {
				LOG.info("\t%s",
						step.toString(false, false, dataItemModel.getTheta()));
			}
		}
	}
	
	/**
	 * runs parser on all data once without making any parameter updates;
	 * this lets us see how the model does only on the seed lexicon
	 */
	protected void runInitialModel(Model<SAMPLE, MR> model){
		System.out.println("========================="
							+ "Running initial model..." + ""
							+ "=========================");
		
		int itemCounter = 0;
		int numCorrects = 0;
		int numFailures = 0;
		for (final DI dataItem : trainingData) {
			// Data item model
			final IDataItemModel<MR> dataItemModel = model.createDataItemModel(dataItem.getSample());
			
			// Parse with current model and record some statistics
			final PO parserOutput = parse(dataItem, dataItemModel);
			parserOutputLogger.log(parserOutput, dataItemModel, String
							.format("train-%d-%d", 0, itemCounter));
	
			final List<? extends IDerivation<MR>> modelParses = parserOutput.getAllDerivations();
	
			LOG.info("Model parsing time: %.4fsec",
					parserOutput.getParsingTime() / 1000.0);
			LOG.info("Output is %s",
					parserOutput.isExact() ? "exact" : "approximate");
			LOG.info("Created %d model parses for training sample:",
					modelParses.size());
			for (final IDerivation<MR> parse : modelParses) {
				try {
					logParse(dataItem, parse,
							validate(dataItem, parse.getSemantics()), true,
							dataItemModel);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
			
			// Create a list of all valid parses
			final List<? extends IDerivation<MR>> validParses = getValidParses(parserOutput, dataItem);
			
			numCorrects += validParses.size() > 0 ? 1 : 0; // at least one valid parse
			numFailures += modelParses.size() == 0 ? 1 : 0; // no parses found
		}
		
		// precision = # correct / total # parsed
		final double precision = trainingData.size() - numFailures == 0.0 ? 0.0
														: (double) numCorrects / (trainingData.size() - numFailures);
		// recall = # correct / total # examples
		final double recall = trainingData.size() == 0 ? 0.0 : (double) numCorrects / trainingData.size();
		final double f1 = precision + recall == 0.0 ? 0.0
												: ( 2 * precision * recall ) / (precision + recall);
		
		System.out.println("initial stats:"
							+ "\n\tprecision: " + precision
							+ "\n\trecall: " + recall 
							+ "\n\tf1: " + f1);
	}
	
	

	/**
	 * Parameter update method.
	 */
	protected abstract void parameterUpdate(DI dataItem, PO realOutput,
			PO goodOutput, Model<SAMPLE, MR> model,
			//List<? extends IDerivation<MR>> validParses,
			int itemCounter, int epochNumber, boolean noisyExample);

	/**
	 * Unconstrained parsing method.
	 */
	protected abstract PO parse(DI dataItem, IDataItemModel<MR> dataItemModel);

	/**
	 * Constrained parsing method.
	 */
	protected abstract PO parse(DI dataItem,
			Predicate<ParsingOp<MR>> pruningFilter,
			IDataItemModel<MR> dataItemModel);

	/**
	 * Constrained parsing method for lexical generation.
	 */
	protected abstract PO parse(DI dataItem,
			Predicate<ParsingOp<MR>> pruningFilter,
			IDataItemModel<MR> dataItemModel,
			ILexiconImmutable<MR> generatedLexicon, Integer beamSize);

	/**
	 * Validation method.
	 */
	abstract protected boolean validate(DI dataItem, MR hypothesis) throws MalformedURLException, IOException;
}
