a :- NP/N : (lambda $0:<e,t> (lambda $1:e ($0 $1)))
green :- N/N : (lambda $0:<e,t> (lambda $1:e (and:<t*,t> (green:<e,t> $1) ($0 $1))))
backpack :- N : (bag:<e,t>)
is :- ((S\NP)/NP)/NP : (lambda $0:<e,<e,t>> (lambda $1:<e,<e,t>> (lambda $2:<e,t> (lambda $3:e (lambda $4:e (lambda $5:e (and:<t*,t> ($0 $3 $4) ($2 $3) ($1 $3 $5))))))))
near :- NP/NP : (lambda $0:<e,t> (lambda $1:e (lambda $2:e (and:<t*,t> ($0 $2) (near:<e,<e,t>> $1 $2)))))
the :- NP/N : (lambda $0:<e,t> (lambda $1:e ($0 $1)))
stairway :- N : (stairs:<e,t>)
on :- NP/NP : (lambda $0:<e,t> (lambda $1:e (lambda $2:e (and:<t*,t> ($0 $2) (on:<e,<e,t>> $1 $2))))
floor :- NP : (floor:<e,t>)
