the :- NP/N : (lambda $0:<e,t> (lambda $1:e ($0 $1)))
man :- N : (person:<e,t>)
lifting :- (NP\NP)/NP : (lambda $0:<e,t> (lambda $1:<e,t> (lambda $2:e (lambda $3:e (and:<t*,t> ($0 $3) ($1 $2) (pick_up:<e,<e,t>> $2 $3))))))
chair :- N : (chair:<e,t>)
is :- (S\NP)/(S\NP) : (lambda $0:<e,<e,t>> (lambda $1:<e,<e,t>> (lambda $2:e (lambda $3:e (lambda $4:e (and:<t*,t> ($1 $2 $3) ($0 $2 $4)))))))
wearing :- (S\NP)/NP : (lambda $0:<e,t> (lambda $1:e (lambda $2:e (and:<t*,t> ($0 $2) (wear:<e,<e,t>> $1 $2)))))
a :- NP/N : (lambda $0:<e,t> (lambda $1:e ($0 $1)))
plaid :- N/N : (lambda $0:<e,t> (lambda $1:e (and:<t*,t> (plaid:<e,t> $1) ($0 $1))))
shirt :- N : (shirt:<e,t>)
