a :- NP/N : (lambda $0:<e,t> (lambda $1:e ($0 $1)))
man :- N : (person:<e,t>)
walks :- (S\NP)/NP : (lambda $0:<e,<e,t>> (lambda $1:<e,t> (lambda $2:e (lambda $3:e (lambda $4:e (and:<t*,t> ($1 $2) ($0 $3 $4) (walk:<e,t> $2)))))))
yellow :- N/N : (lambda $0:<e,t> (lambda $1:e (and:<t*,t> (yellow:<e,t> $1) ($0 $1))))
chair :- N : (chair:<e,t>)
over to :- (NP\NP)/NP : (lambda $0:<e,t> (lambda $1:<e,t> (lambda $2:e (lambda $3:e (and:<t*,t> ($0 $3) ($1 $2) (to:<e,<e,t>> $2 $3))))))
another :- NP/N : (lambda $0:<e,t> (lambda $1:e ($0 $1)))
