a :- NP/N : (lambda $0:<e,t> (lambda $1:e ($0 $1)))
woman :- N : (person:<e,t>)
cautiously :- (S\NP)/(S\NP) : (lambda $0:<e,<e,t>> (lambda $1:<e,t> (lambda $2:e (lambda $3:e (and:<t*,t> ($1 $2) ($0 $2 $3))))))
grabs :- (S\NP)/NP : (lambda $0:<e,t> (lambda $1:e (lambda $2:e (and:<t*,t> ($0 $2) (pick_up:<e,<e,t>> $1 $2)))))
an :- NP/N : (lambda $0:<e,t> (lambda $1:e ($0 $1)))
apple :- N : (apple:<e,t>)
off :- (S\S)/NP : (lambda $0:<e,t> (lambda $1:<e,<e,t>> (lambda $2:e (lambda $3:e (lambda $4:e (and:<t*,t> ($1 $2 $3) ($0 $4) (from:<e,<e,t>> $3 $4)))))))
the :- NP/N : (lambda $0:<e,t> (lambda $1:e ($0 $1)))
table :- N : (table:<e,t>)
