the :- NP/N : (lambda $0:<e,t> (lambda $1:e ($0 $1)))
guy :- N : (person:<e,t>)
in :- (NP\NP)/NP : (lambda $0:<e,t> (lambda $1:<e,t> (lambda $2:e (lambda $3:e (and:<t*,t> ($1 $2) ($0 $3) (in:<e,<e,t>> $2 $3))))))
plaid :- N/N : (lambda $0:<e,t> (lambda $1:e (and:<t*,t> (plaid:<e,t> $1) ($0 $1))))
shirt :- N : (shirt:<e,t>)
walks :- (S\NP)/NP : (lambda $0:<e,<e,t>> (lambda $1:<e,<e,t>> (lambda $2:e (lambda $3:e (lambda $4:e (and:<t*,t> ($1 $2 $3) ($0 $2 $4) (walk:<e,t> $2)))))))
toward :- NP/NP : (lambda $0:<e,t> (lambda $1:e (lambda $2:e (and:<t*,t> ($0 $2) (toward:<e,<e,t>> $1 $2)))))
tan :- N/N : (lambda $0:<e,t> (lambda $1:e (and:<t*,t> (tan:<e,t> $1) ($0 $1))))
chair :- N : (chair:<e,t>)
